FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY app.js /usr/share/nginx/html/app.js
COPY tailwind.css /usr/share/nginx/html/tailwind.css
COPY i18n.js i18n-en.js /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
