#!/bin/bash
# Generate a fail2ban jail for APS Vault and (optionally) install it.
#
#   ops/fail2ban/gen-jail.sh                                  # print jail.d/aps-vault.local to stdout
#   ops/fail2ban/gen-jail.sh --install                        # write filter + jail, reload fail2ban
#   LOGPATH=/srv/aps-vault/data/security.log PORTS=443 MAXRETRY=5 FINDTIME=15m BANTIME=1h ops/fail2ban/gen-jail.sh
#
# The vault writes one line per failed attempt to VAULT_SECURITY_LOG (mount data/ on the host
# so fail2ban can read it). The vault's own lock-out (5 per IP / 15 min, persisted) keeps
# working; fail2ban adds a network-level ban in front of the reverse proxy.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
LOGPATH="${LOGPATH:-$(cd "$HERE/../.." && pwd)/data/security.log}"
PORTS="${PORTS:-http,https}"
MAXRETRY="${MAXRETRY:-5}"
FINDTIME="${FINDTIME:-15m}"
BANTIME="${BANTIME:-1h}"
ACTION="${ACTION:-%(action_)s}"      # e.g. "%(action_mwl)s" to also mail

jail=$(cat <<EOF
# generated by aps-vault ops/fail2ban/gen-jail.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
[aps-vault]
enabled  = true
filter   = aps-vault
logpath  = $LOGPATH
port     = $PORTS
maxretry = $MAXRETRY
findtime = $FINDTIME
bantime  = $BANTIME
action   = $ACTION
EOF
)

if [ "${1:-}" = "--install" ]; then
  install -m 644 "$HERE/aps-vault.conf" /etc/fail2ban/filter.d/aps-vault.conf
  printf '%s\n' "$jail" > /etc/fail2ban/jail.d/aps-vault.local
  [ -f "$LOGPATH" ] || { install -m 644 /dev/null "$LOGPATH"; }
  fail2ban-client reload >/dev/null && fail2ban-client status aps-vault
else
  printf '%s\n' "$jail"
fi
