#!/usr/bin/env python3
"""Generate the GOST constant tables for the Node, Go and Java clients from one JSON source
(scratch: produced from the MIT `gostcrypto` tables and backend/gost.py), so no table is ever
typed by hand. Usage: python3 ops/gen-gost-consts.py <consts.json>"""
import json
import sys

src = json.load(open(sys.argv[1]))
T = src["streebog_T"]            # 8 × 256 uint64
C = src["streebog_C"]            # 12 × 64 bytes (hex)
PI = src["kuznyechik_pi"]        # 256 bytes
CURVE = src["curve"]             # hex strings

HEADER = "GENERATED by ops/gen-gost-consts.py — Streebog T/C tables (GOST R 34.11-2012, from the MIT gostcrypto package), Kuznyechik π (GOST R 34.12-2015), curve id-tc26-gost-3410-2012-256-paramSetB. Do not edit."


def ts():
    out = [f"// {HEADER}", "export const STREEBOG_T: bigint[][] = ["]
    for row in T:
        out.append("  [" + ", ".join(f"0x{v:016x}n" for v in row) + "],")
    out.append("];")
    out.append("export const STREEBOG_C: Uint8Array[] = [")
    for c in C:
        out.append(f"  Uint8Array.from(Buffer.from('{c}', 'hex')),")
    out.append("];")
    out.append("export const KUZNYECHIK_PI = Uint8Array.from([" + ", ".join(str(v) for v in PI) + "]);")
    out.append("export const CURVE = {")
    for k, v in CURVE.items():
        out.append(f"  {k}: {v}n,")
    out.append("};")
    return "\n".join(out) + "\n"


def go():
    out = ["package vault", "", f"// {HEADER}", "", "var streebogT = [8][256]uint64{"]
    for row in T:
        out.append("\t{" + ", ".join(f"0x{v:016x}" for v in row) + "},")
    out.append("}")
    out.append("")
    out.append("var streebogC = [12][64]byte{")
    for c in C:
        b = bytes.fromhex(c)
        out.append("\t{" + ", ".join(f"0x{x:02x}" for x in b) + "},")
    out.append("}")
    out.append("")
    out.append("var kuznyechikPi = [256]byte{" + ", ".join(str(v) for v in PI) + "}")
    out.append("")
    out.append("const (")
    width = max(len(k) for k in CURVE)
    for k, v in CURVE.items():                     # gofmt-aligned `=`
        out.append(f'\tcurve{k.ljust(width)} = "{v[2:]}"')
    out.append(")")
    return "\n".join(out) + "\n"


def java():
    out = ["package io.apsvault;", "", f"// {HEADER}", "final class GostConsts {", "    private GostConsts() {}", "", "    static final long[][] STREEBOG_T = {"]
    for row in T:
        out.append("        {" + ", ".join(f"0x{v:016x}L" for v in row) + "},")
    out.append("    };")
    out.append("    static final byte[][] STREEBOG_C = {")
    for c in C:
        b = bytes.fromhex(c)
        out.append("        {" + ", ".join(f"(byte) 0x{x:02x}" for x in b) + "},")
    out.append("    };")
    out.append("    static final int[] KUZNYECHIK_PI = {" + ", ".join(str(v) for v in PI) + "};")
    for k, v in CURVE.items():
        out.append(f'    static final String CURVE_{k} = "{v[2:]}";')
    out.append("}")
    return "\n".join(out) + "\n"


open("clients/node/src/gost-consts.ts", "w").write(ts())
open("clients/go/gost_consts.go", "w").write(go())
open("clients/java/src/main/java/io/apsvault/GostConsts.java", "w").write(java())
print("written: clients/node/src/gost-consts.ts clients/go/gost_consts.go clients/java/src/main/java/io/apsvault/GostConsts.java")
